debug: true
server:
  port: 8080
  servlet:
    context-path: /
     
spring:
  datasource:
    password: 
    url: jdbc:mysql://localhost:3306/bentouis?serverTimezone=UTC
    username: root
    
  jpa:
    hibernate:
      ddl-auto: none
 
  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: Face ID
          clientSecret: Face SECRET
          scope:
           - email
           - public_profile      